project_id: observatorio-ino-1
dataset_id: clisueno
table_id: tbl_xpap
write_disposition: WRITE_APPEND
service_account_json: load/secrets/obsino-clisueno.json
source_excel_path: load/stg_clisueno_xpap_2025.xlsx
source_sheet_name: Data_xpap2025
schema_yaml_path: load/schema_xpap.yaml

# Campos operativos compartidos de la carga manual
uuid_field: basal_uuid
date_field: basal_fecha_estudio
migrated_field: basal_migrado
