entrada:
  ruta: "../../staging"

procesamiento:
  tipos_validos: ["docx", "doc", "rtf"]
  glob_patron: "**/*"
  barra_progreso: true

salida:
  carpeta_csv: "../../staging"

subflujos:
  salida_unificada:
    BASAL: "unificado_basal.csv"
  prefijos:
    BASAL: "bs"

logging:
  level: "INFO"
  dir: "/home/rom/obsino/clisueno/logs"
