entrada:
  ruta: "../../staging"

procesamiento:
  tipos_validos: ["docx", "doc", "rtf"]
  glob_patron: "**/*"
  barra_progreso: true

salida:
  carpeta_csv: "../../staging"

subflujos:
  salida_unificada:
    CPAP: "unificado_xpap.csv"
    BPAP: "unificado_xpap.csv"
  prefijos:
    CPAP: "xp"
    BPAP: "xp"

logging:
  level: "INFO"
  dir: "/home/rom/obsino/clisueno/logs"
